spring:
  application:
    name: query-stack
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  main:
    banner-mode: off

#logging:
#  level:
#    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs    # Path to access the OpenAPI JSON
  swagger-ui:
    path: /swagger-ui.html  # Path to access the Swagger UI

query-stack:
  schema-path: /schema/plan-schema.json
